# Generated by Django 3.2.5 on 2021-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ContactNo',
            field=models.PositiveBigIntegerField(),
        ),
    ]
