# Generated by Django 3.2.5 on 2021-08-02 18:55

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210801_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_default', models.TextField()),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_custom', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('body_textfield', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
    ]
