# Generated by Django 3.2.5 on 2021-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210911_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Country',
            new_name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
